A = 10
B = 12
C = 0
if A and B and C :
    print ("ALL THE NUMBERS HAVE BOOLEAN AS TRUE")
else :
    print ("AT LEAST ALL THE NUMBERS HAVE BOOLEAN AS FALSE")

a = 10
b = -10
c =0
if a > 0 or b > 0:
    print ("either of the number is greater than zero")
else :
    print ("no number is greater than zero")

if b > 0 or c > 0:
    print ("either of the number is greater than zero")
else :
    print ("no number is greater than zero")